-- NRSC Worship — song database and set lists.
-- Run once in Supabase: SQL Editor → paste this whole file → Run. Safe to run again.
--
-- The app never talks to these tables from the browser. The Vercel /api functions
-- call the functions below with the service key, so every save is one atomic step
-- (a song and its themes, a set list and its songs) and the tables stay private.

create extension if not exists pg_trgm;

-- ------------------------------------------------------------------ tables

create table if not exists public.themes (
  id bigint generated by default as identity primary key,
  name text not null check (length(trim(name)) between 1 and 60),
  description text,
  created_at timestamptz not null default now()
);
create unique index if not exists themes_name_key on public.themes (lower(name));

create table if not exists public.songs (
  id bigint generated by default as identity primary key,
  title text not null check (length(trim(title)) between 1 and 200),
  title_alt text,
  language text not null default 'luganda' check (language in ('luganda', 'english', 'both')),
  lyrics_luganda text,
  lyrics_english text,
  session text not null default 'praise' check (session in ('praise', 'worship')),
  song_key text,
  tempo_bpm integer check (tempo_bpm is null or tempo_bpm between 30 and 260),
  youtube_url text check (youtube_url is null or youtube_url ~* '^https?://'),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists songs_title_idx on public.songs (lower(title));
create index if not exists songs_search_idx on public.songs using gin (
  (coalesce(title, '') || ' ' || coalesce(title_alt, '') || ' ' || coalesce(lyrics_luganda, '') || ' ' || coalesce(lyrics_english, '')) gin_trgm_ops
);

create table if not exists public.song_themes (
  song_id bigint not null references public.songs (id) on delete cascade,
  theme_id bigint not null references public.themes (id) on delete cascade,
  primary key (song_id, theme_id)
);
create index if not exists song_themes_theme_idx on public.song_themes (theme_id);

create table if not exists public.set_lists (
  id bigint generated by default as identity primary key,
  service_date date not null,
  theme_id bigint references public.themes (id) on delete set null,
  title text,
  leader_name text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists set_lists_date_idx on public.set_lists (service_date desc);

create table if not exists public.set_list_songs (
  id bigint generated by default as identity primary key,
  set_list_id bigint not null references public.set_lists (id) on delete cascade,
  song_id bigint not null references public.songs (id) on delete cascade,
  section text not null check (section in ('praise', 'worship')),
  position integer not null check (position >= 1)
);
create index if not exists set_list_songs_set_idx on public.set_list_songs (set_list_id, section, position);
create index if not exists set_list_songs_song_idx on public.set_list_songs (song_id);

-- Private: only the service key (used by the /api functions) can read or write.
alter table public.themes enable row level security;
alter table public.songs enable row level security;
alter table public.song_themes enable row level security;
alter table public.set_lists enable row level security;
alter table public.set_list_songs enable row level security;

-- ------------------------------------------------------------------ seed themes

insert into public.themes (name)
select t.name
from (values ('Glory of God'), ('Love of God'), ('Prayer'), ('Thanksgiving'), ('Revival'),
             ('Holy Spirit'), ('Salvation'), ('Faith'), ('Praise & Victory')) as t (name)
where not exists (select 1 from public.themes x where lower(x.name) = lower(t.name));

-- ------------------------------------------------------------------ helpers

-- Blank strings become null, everything is trimmed.
create or replace function public.nw_text(p jsonb, k text) returns text
language sql immutable as $$
  select nullif(trim(p ->> k), '')
$$;

-- Short excerpt of `p_text` around the first match of `p_q` (case-insensitive), for search results.
create or replace function public.nw_snippet(p_text text, p_q text) returns text
language sql immutable as $$
  select case
    when p_text is null or coalesce(p_q, '') = '' or strpos(lower(p_text), lower(p_q)) = 0 then null
    else (
      select (case when pos > 40 then '…' else '' end)
          || regexp_replace(substr(p_text, greatest(1, pos - 40), length(p_q) + 90), '\s+', ' ', 'g')
          || (case when pos + length(p_q) + 50 < length(p_text) then '…' else '' end)
      from (select strpos(lower(p_text), lower(p_q)) as pos) x
    )
  end
$$;

create or replace function public.nw_song_json(s public.songs) returns jsonb
language sql stable as $$
  select jsonb_build_object(
    'id', s.id, 'title', s.title, 'title_alt', s.title_alt, 'language', s.language,
    'lyrics_luganda', s.lyrics_luganda, 'lyrics_english', s.lyrics_english,
    'session', s.session, 'song_key', s.song_key, 'tempo_bpm', s.tempo_bpm,
    'youtube_url', s.youtube_url, 'notes', s.notes,
    'created_at', s.created_at, 'updated_at', s.updated_at,
    'themes', coalesce((
      select jsonb_agg(jsonb_build_object('id', t.id, 'name', t.name) order by lower(t.name))
      from public.song_themes st join public.themes t on t.id = st.theme_id
      where st.song_id = s.id), '[]'::jsonb)
  )
$$;

-- ------------------------------------------------------------------ songs

-- Library list: everything a card needs, without lyrics (keeps it small on slow data).
create or replace function public.list_songs() returns jsonb
language sql stable as $$
  select coalesce(jsonb_agg(jsonb_build_object(
      'id', s.id, 'title', s.title, 'title_alt', s.title_alt, 'language', s.language,
      'session', s.session, 'song_key', s.song_key, 'tempo_bpm', s.tempo_bpm,
      'has_luganda', coalesce(length(trim(s.lyrics_luganda)), 0) > 0,
      'has_english', coalesce(length(trim(s.lyrics_english)), 0) > 0,
      'has_youtube', s.youtube_url is not null,
      'theme_ids', coalesce((select jsonb_agg(st.theme_id order by st.theme_id)
                             from public.song_themes st where st.song_id = s.id), '[]'::jsonb),
      'updated_at', s.updated_at
    ) order by lower(s.title), s.id), '[]'::jsonb)
  from public.songs s
$$;

-- Search titles and both lyric parts. Returns [{id, match: title|luganda|english, snippet}].
create or replace function public.search_songs(p_q text, p_limit integer default 60) returns jsonb
language sql stable as $$
  with q as (
    select trim(coalesce(p_q, '')) as raw,
           '%' || replace(replace(replace(trim(coalesce(p_q, '')), '\', '\\'), '%', '\%'), '_', '\_') || '%' as pat
  ),
  hits as (
    select s.id, s.title,
      case
        when s.title ilike q.pat or coalesce(s.title_alt, '') ilike q.pat then 'title'
        when coalesce(s.lyrics_luganda, '') ilike q.pat then 'luganda'
        when coalesce(s.lyrics_english, '') ilike q.pat then 'english'
      end as field,
      s.lyrics_luganda, s.lyrics_english, q.raw
    from public.songs s, q
    where length(q.raw) > 0
  )
  select coalesce(jsonb_agg(jsonb_build_object(
      'id', h.id, 'match', h.field,
      'snippet', case h.field when 'luganda' then public.nw_snippet(h.lyrics_luganda, h.raw)
                              when 'english' then public.nw_snippet(h.lyrics_english, h.raw) end
    ) order by (h.field = 'title') desc, lower(h.title)), '[]'::jsonb)
  from (select * from hits where field is not null
        order by (field = 'title') desc, lower(title)
        limit greatest(1, least(coalesce(p_limit, 60), 200))) h
$$;

create or replace function public.get_song(p_id bigint) returns jsonb
language sql stable as $$
  select public.nw_song_json(s) from public.songs s where s.id = p_id
$$;

-- Create (no id) or update (with id) a song and replace its themes, in one transaction.
create or replace function public.save_song(p jsonb) returns jsonb
language plpgsql as $$
declare
  v_id bigint := nullif(p ->> 'id', '')::bigint;
begin
  if public.nw_text(p, 'title') is null then
    raise exception 'title_required';
  end if;
  if v_id is null then
    insert into public.songs (title, title_alt, language, lyrics_luganda, lyrics_english, session,
                              song_key, tempo_bpm, youtube_url, notes)
    values (public.nw_text(p, 'title'), public.nw_text(p, 'title_alt'),
            coalesce(public.nw_text(p, 'language'), 'luganda'),
            public.nw_text(p, 'lyrics_luganda'), public.nw_text(p, 'lyrics_english'),
            coalesce(public.nw_text(p, 'session'), 'praise'),
            public.nw_text(p, 'song_key'), nullif(p ->> 'tempo_bpm', '')::integer,
            public.nw_text(p, 'youtube_url'), public.nw_text(p, 'notes'))
    returning id into v_id;
  else
    update public.songs set
      title = public.nw_text(p, 'title'),
      title_alt = public.nw_text(p, 'title_alt'),
      language = coalesce(public.nw_text(p, 'language'), 'luganda'),
      lyrics_luganda = public.nw_text(p, 'lyrics_luganda'),
      lyrics_english = public.nw_text(p, 'lyrics_english'),
      session = coalesce(public.nw_text(p, 'session'), 'praise'),
      song_key = public.nw_text(p, 'song_key'),
      tempo_bpm = nullif(p ->> 'tempo_bpm', '')::integer,
      youtube_url = public.nw_text(p, 'youtube_url'),
      notes = public.nw_text(p, 'notes'),
      updated_at = now()
    where id = v_id;
    if not found then
      raise exception 'not_found';
    end if;
  end if;

  if p ? 'theme_ids' then
    delete from public.song_themes where song_id = v_id;
    insert into public.song_themes (song_id, theme_id)
    select distinct v_id, t.id
    from jsonb_array_elements_text(coalesce(p -> 'theme_ids', '[]'::jsonb)) x (v)
    join public.themes t on t.id = x.v::bigint;
  end if;

  return public.get_song(v_id);
end $$;

create or replace function public.delete_song(p_id bigint) returns jsonb
language plpgsql as $$
begin
  delete from public.songs where id = p_id;
  return jsonb_build_object('deleted', found);
end $$;

-- Bulk import. Rows are already parsed and checked by the API: [{title, ..., theme_ids}].
-- p_mode 'skip' leaves songs with an existing title alone; 'update' fills them in
-- (non-empty imported fields replace, themes are added).
create or replace function public.import_songs(p_rows jsonb, p_mode text default 'skip') returns jsonb
language plpgsql as $$
declare
  r jsonb;
  v_id bigint;
  created integer := 0;
  updated integer := 0;
  skipped jsonb := '[]'::jsonb;
begin
  for r in select * from jsonb_array_elements(coalesce(p_rows, '[]'::jsonb)) loop
    if public.nw_text(r, 'title') is null then
      continue;
    end if;
    select id into v_id from public.songs where lower(title) = lower(public.nw_text(r, 'title')) order by id limit 1;
    if v_id is null then
      v_id := (public.save_song(r - 'id') ->> 'id')::bigint;
      created := created + 1;
    elsif p_mode = 'update' then
      update public.songs set
        title_alt = coalesce(public.nw_text(r, 'title_alt'), title_alt),
        language = coalesce(public.nw_text(r, 'language'), language),
        lyrics_luganda = coalesce(public.nw_text(r, 'lyrics_luganda'), lyrics_luganda),
        lyrics_english = coalesce(public.nw_text(r, 'lyrics_english'), lyrics_english),
        session = coalesce(public.nw_text(r, 'session'), session),
        song_key = coalesce(public.nw_text(r, 'song_key'), song_key),
        tempo_bpm = coalesce(nullif(r ->> 'tempo_bpm', '')::integer, tempo_bpm),
        youtube_url = coalesce(public.nw_text(r, 'youtube_url'), youtube_url),
        notes = coalesce(public.nw_text(r, 'notes'), notes),
        updated_at = now()
      where id = v_id;
      insert into public.song_themes (song_id, theme_id)
      select distinct v_id, t.id
      from jsonb_array_elements_text(coalesce(r -> 'theme_ids', '[]'::jsonb)) x (v)
      join public.themes t on t.id = x.v::bigint
      on conflict do nothing;
      updated := updated + 1;
    else
      skipped := skipped || to_jsonb(public.nw_text(r, 'title'));
    end if;
  end loop;
  return jsonb_build_object('created', created, 'updated', updated, 'skipped', skipped);
end $$;

-- ------------------------------------------------------------------ themes

create or replace function public.list_themes() returns jsonb
language sql stable as $$
  select coalesce(jsonb_agg(jsonb_build_object(
      'id', t.id, 'name', t.name, 'description', t.description,
      'song_count', (select count(*) from public.song_themes st where st.theme_id = t.id)
    ) order by lower(t.name)), '[]'::jsonb)
  from public.themes t
$$;

create or replace function public.save_theme(p jsonb) returns jsonb
language plpgsql as $$
declare
  v_id bigint := nullif(p ->> 'id', '')::bigint;
begin
  if public.nw_text(p, 'name') is null then
    raise exception 'name_required';
  end if;
  begin
    if v_id is null then
      insert into public.themes (name, description)
      values (public.nw_text(p, 'name'), public.nw_text(p, 'description'))
      returning id into v_id;
    else
      update public.themes set name = public.nw_text(p, 'name'), description = public.nw_text(p, 'description')
      where id = v_id;
      if not found then
        raise exception 'not_found';
      end if;
    end if;
  exception when unique_violation then
    raise exception 'theme_exists';
  end;
  return (select jsonb_build_object('id', t.id, 'name', t.name, 'description', t.description)
          from public.themes t where t.id = v_id);
end $$;

create or replace function public.delete_theme(p_id bigint) returns jsonb
language plpgsql as $$
begin
  delete from public.themes where id = p_id;
  return jsonb_build_object('deleted', found);
end $$;

-- ------------------------------------------------------------------ set lists

create or replace function public.get_set_list(p_id bigint) returns jsonb
language sql stable as $$
  select jsonb_build_object(
    'id', l.id, 'service_date', l.service_date, 'title', l.title, 'leader_name', l.leader_name,
    'notes', l.notes, 'updated_at', l.updated_at,
    'theme', case when t.id is null then null else jsonb_build_object('id', t.id, 'name', t.name) end,
    'items', coalesce((
      select jsonb_agg(jsonb_build_object(
          'section', i.section, 'position', i.position,
          'song', jsonb_build_object('id', s.id, 'title', s.title, 'title_alt', s.title_alt,
                                     'song_key', s.song_key, 'session', s.session, 'language', s.language))
        order by (i.section = 'worship'), i.position)
      from public.set_list_songs i join public.songs s on s.id = i.song_id
      where i.set_list_id = l.id), '[]'::jsonb)
  )
  from public.set_lists l left join public.themes t on t.id = l.theme_id
  where l.id = p_id
$$;

create or replace function public.list_set_lists(p_limit integer default 40) returns jsonb
language sql stable as $$
  select coalesce(jsonb_agg(x order by x ->> 'service_date' desc, (x ->> 'id')::bigint desc), '[]'::jsonb)
  from (
    select jsonb_build_object(
      'id', l.id, 'service_date', l.service_date, 'title', l.title, 'leader_name', l.leader_name,
      'theme', case when t.id is null then null else jsonb_build_object('id', t.id, 'name', t.name) end,
      'praise_count', (select count(*) from public.set_list_songs i where i.set_list_id = l.id and i.section = 'praise'),
      'worship_count', (select count(*) from public.set_list_songs i where i.set_list_id = l.id and i.section = 'worship')
    ) as x
    from public.set_lists l left join public.themes t on t.id = l.theme_id
    order by l.service_date desc, l.id desc
    limit greatest(1, least(coalesce(p_limit, 40), 200))
  ) y
$$;

-- Create or update a set list and replace its songs in one transaction.
-- p: {id?, service_date, theme_id?, title?, leader_name?, notes?, items: [{song_id, section}]}
-- Items keep the order given; positions are renumbered 1..n within each section.
create or replace function public.save_set_list(p jsonb) returns jsonb
language plpgsql as $$
declare
  v_id bigint := nullif(p ->> 'id', '')::bigint;
  v_date date;
  v_theme bigint := nullif(p ->> 'theme_id', '')::bigint;
begin
  begin
    v_date := (p ->> 'service_date')::date;
  exception when others then
    raise exception 'date_required';
  end;
  if v_date is null then
    raise exception 'date_required';
  end if;
  if v_theme is not null and not exists (select 1 from public.themes where id = v_theme) then
    v_theme := null;
  end if;

  if v_id is null then
    insert into public.set_lists (service_date, theme_id, title, leader_name, notes)
    values (v_date, v_theme, public.nw_text(p, 'title'), public.nw_text(p, 'leader_name'), public.nw_text(p, 'notes'))
    returning id into v_id;
  else
    update public.set_lists set service_date = v_date, theme_id = v_theme, title = public.nw_text(p, 'title'),
      leader_name = public.nw_text(p, 'leader_name'), notes = public.nw_text(p, 'notes'), updated_at = now()
    where id = v_id;
    if not found then
      raise exception 'not_found';
    end if;
  end if;

  delete from public.set_list_songs where set_list_id = v_id;
  insert into public.set_list_songs (set_list_id, song_id, section, position)
  select v_id, s.id, x.section,
         row_number() over (partition by x.section order by x.ord)
  from jsonb_array_elements(coalesce(p -> 'items', '[]'::jsonb)) with ordinality as e (item, ord)
  cross join lateral (select e.item ->> 'section' as section, e.ord, nullif(e.item ->> 'song_id', '')::bigint as song_id) x
  join public.songs s on s.id = x.song_id
  where x.section in ('praise', 'worship');

  return public.get_set_list(v_id);
end $$;

create or replace function public.delete_set_list(p_id bigint) returns jsonb
language plpgsql as $$
begin
  delete from public.set_lists where id = p_id;
  return jsonb_build_object('deleted', found);
end $$;

-- When each song was last used in a set list since p_since: {"<song_id>": "YYYY-MM-DD"}.
create or replace function public.song_usage(p_since date) returns jsonb
language sql stable as $$
  select coalesce(jsonb_object_agg(u.song_id::text, u.last_used), '{}'::jsonb)
  from (
    select i.song_id, max(l.service_date) as last_used
    from public.set_list_songs i join public.set_lists l on l.id = i.set_list_id
    where l.service_date >= p_since
    group by i.song_id
  ) u
$$;

-- ------------------------------------------------------------------ access
-- Only the server (service_role) may call these. Supabase grants new functions to the
-- public API roles by default, so take that back explicitly.

do $$
declare
  f text;
begin
  foreach f in array array[
    'public.list_songs()', 'public.search_songs(text, integer)', 'public.get_song(bigint)',
    'public.save_song(jsonb)', 'public.delete_song(bigint)', 'public.import_songs(jsonb, text)',
    'public.list_themes()', 'public.save_theme(jsonb)', 'public.delete_theme(bigint)',
    'public.get_set_list(bigint)', 'public.list_set_lists(integer)', 'public.save_set_list(jsonb)',
    'public.delete_set_list(bigint)', 'public.song_usage(date)'
  ] loop
    execute format('revoke execute on function %s from public', f);
    if exists (select 1 from pg_roles where rolname = 'anon') then
      execute format('revoke execute on function %s from anon', f);
    end if;
    if exists (select 1 from pg_roles where rolname = 'authenticated') then
      execute format('revoke execute on function %s from authenticated', f);
    end if;
    if exists (select 1 from pg_roles where rolname = 'service_role') then
      execute format('grant execute on function %s to service_role', f);
    end if;
  end loop;
end $$;

-- Ask the API to pick up the new functions straight away.
notify pgrst, 'reload schema';
